function mrdcdsdfgmckrtp1s = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   MRDCDSDFGMCKRTP1S = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   MRDCDSDFGMCKRTP1S = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   mrdcdsdfgmckrtp1s = importfile('05358_mrdcd_sdfgmc_krtp_1s.asc', 88, 86223);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/10/30 09:16:35

%% Initialize variables.
if nargin<=2
    startRow = 88;
    endRow = inf;
end

%% Format for each line of text:
%   column1: datetimes (%{yyyy MM dd HH mm ss SSS}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%25{yyyy MM dd HH mm ss SSS}D%10f%13f%14f%13f%15f%14f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
mrdcdsdfgmckrtp1s = table(dataArray{1:end-1}, 'VariableNames', {'Fechahora','Bx_nT','By_nT','Bz_nT','Bmag_nT','x_km','y_km','z_km'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% mrdcdsdfgmckrtp1s.Fechahora=datenum(mrdcdsdfgmckrtp1s.Fechahora);

